---
- hosts: zookeeper-nodes
  pre_tasks:
    - name: Install Java 8 (OpenJDK)
      apt:
        name: java-1.8.0-openjdk
        state: installed
      tags:
        - requirements
  roles:
    - role: ansible-zookeeper
