---
- hosts: zookeeper-nodes
  pre_tasks:
    - name: Install Java 8 (OpenJDK)
      apt:
        name: openjdk-8-jre-headless
        state: present
      tags:
        - requirements
  roles:
    - role: ansible-zookeeper
